In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/raw_customers.csv')
df

    customer_id  age    income    city plan_type  churned
0          2001   25   32000.0    Pune     Basic        1
1          2002   45       NaN   Delhi   Premium        0
2          2003   35   48000.0    Pune  Standard        1
3          2004   50   95000.0  Mumbai   Premium        0
4          2005   23       NaN   Delhi     Basic        1
5          2006   41   72000.0  Mumbai  Standard        0
6          2007   33       NaN    Pune     Basic        1
7          2008   60  110000.0   Delhi   Premium        0
8          2009   29   29000.0  Mumbai     Basic        1
9          2010   54   89000.0    Pune   Premium        0
10         2011   31   45000.0   Delhi  Standard        0
11         2012   38       NaN  Mumbai     Basic        1
12         2013   47   91000.0    Pune   Premium        0
13         2014   27       NaN   Delhi     Basic        1
14         2015   44   76000.0  Mumbai  Standard        0
15         2016   36   43000.0    Pune       NaN        1
16         2017   52   93000.0   Delhi   Premium        0
17         2018   24   18000.0  Mumbai     Basic        1
18         2019   40       NaN    Pune  Standard        0
19         2020   32   36000.0   Delhi       NaN        1
20         2021   58   99000.0  Mumbai   Premium        0
21         2022   26   21000.0    Pune     Basic        1
22         2023   43   74000.0   Delhi  Standard        0
23         2024   34       NaN  Mumbai     Basic        1
24         2025   49   86000.0    Pune   Premium        0
25         2026   22   15000.0   Delhi     Basic        1
26         2027   39   67000.0  Mumbai  Standard        0
27         2028   30       NaN    Pune     Basic        1
28         2029   56   97000.0   Delhi   Premium        0
29         2030   28   20000.0  Mumbai     Basic        1

In [3]:
df.isnull().sum()

customer_id    0
age            0
income         8
city           0
plan_type      2
churned        0
dtype: int64

In [4]:
df.dtypes

customer_id      int64
age              int64
income         float64
city            object
plan_type       object
churned          int64
dtype: object

In [5]:
df['city'].value_counts()

city
Pune      10
Delhi     10
Mumbai    10
Name: count, dtype: int64

In [6]:
df['customer_id'].value_counts()

customer_id
2001    1
2002    1
2003    1
2004    1
2005    1
2006    1
2007    1
2008    1
2009    1
2010    1
2011    1
2012    1
2013    1
2014    1
2015    1
2016    1
2017    1
2018    1
2019    1
2020    1
2021    1
2022    1
2023    1
2024    1
2025    1
2026    1
2027    1
2028    1
2029    1
2030    1
Name: count, dtype: int64

In [7]:
df['plan_type'].value_counts()

plan_type
Basic       12
Premium      9
Standard     7
Name: count, dtype: int64

In [8]:
df['income'].value_counts()

income
32000.0     1
48000.0     1
95000.0     1
72000.0     1
110000.0    1
29000.0     1
89000.0     1
45000.0     1
91000.0     1
76000.0     1
43000.0     1
93000.0     1
18000.0     1
36000.0     1
99000.0     1
21000.0     1
74000.0     1
86000.0     1
15000.0     1
67000.0     1
97000.0     1
20000.0     1
Name: count, dtype: int64

In [9]:
df['churned'].value_counts()

churned
1    15
0    15
Name: count, dtype: int64

Building a pipeline. import pipeline from sklearn.pipeline
from sk learn impute import simple imputer

In [10]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [11]:
numeric_features = ['income']
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median'))
])

In [15]:
from sklearn.preprocessing import OneHotEncoder
categorical_features = ['city', 'plan_type']
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder())
])

In [17]:
from sklearn.model_selection import train_test_split
X = df.drop('churned', axis=1)
y = df['churned']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48, stratify=y)

In [22]:
from sklearn.compose import ColumnTransformer
preproccesor = ColumnTransformer(transformers = [('numerical', numeric_transformer, numeric_features), ('categorical', categorical_transformer, categorical_features)])
preproccesor

ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['income']),
                                ('categorical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot', OneHotEncoder())]),
                                 ['city', 'plan_type'])])

In [24]:
X_train_imputed =preproccesor.fit(X_train)
X_train_imputed

ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['income']),
                                ('categorical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot', OneHotEncoder())]),
                                 ['city', 'plan_type'])])

In [26]:
X_train_transformed=preproccesor.transform(X_train)
X_train

    customer_id  age   income    city plan_type
12         2013   47  91000.0    Pune   Premium
10         2011   31  45000.0   Delhi  Standard
29         2030   28  20000.0  Mumbai     Basic
26         2027   39  67000.0  Mumbai  Standard
18         2019   40      NaN    Pune  Standard
16         2017   52  93000.0   Delhi   Premium
20         2021   58  99000.0  Mumbai   Premium
4          2005   23      NaN   Delhi     Basic
19         2020   32  36000.0   Delhi       NaN
6          2007   33      NaN    Pune     Basic
9          2010   54  89000.0    Pune   Premium
11         2012   38      NaN  Mumbai     Basic
17         2018   24  18000.0  Mumbai     Basic
8          2009   29  29000.0  Mumbai     Basic
22         2023   43  74000.0   Delhi  Standard
14         2015   44  76000.0  Mumbai  Standard
2          2003   35  48000.0    Pune  Standard
5          2006   41  72000.0  Mumbai  Standard
25         2026   22  15000.0   Delhi     Basic
28         2029   56  97000.0   Delhi   Premium
27         2028   30      NaN    Pune     Basic
15         2016   36  43000.0    Pune       NaN
21         2022   26  21000.0    Pune     Basic
24         2025   49  86000.0    Pune   Premium

In [27]:
X_train_transformed

array([[9.1e+04, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00],
       [4.5e+04, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00],
       [2.0e+04, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [6.7e+04, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00],
       [6.7e+04, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00],
       [9.3e+04, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00],
       [9.9e+04, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00],
       [6.7e+04, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [3.6e+04, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [6.7e+04, 0.0e+00, 0.0e+00, 1.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [8.9e+04, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00],
       [6.7e+04, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [1.8e+04, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [2.9e+04, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [7.4e+04, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00],
       [7.6e+04, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00],
       [4.8e+04, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00],
       [7.2e+04, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00],
       [1.5e+04, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [9.7e+04, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00],
       [6.7e+04, 0.0e+00, 0.0e+00, 1.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [4.3e+04, 0.0e+00, 0.0e+00, 1.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [2.1e+04, 0.0e+00, 0.0e+00, 1.0e+00, 1.0e+00, 0.0e+00, 0.0e+00],
       [8.6e+04, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00]])

In [28]:
X_train_transformed.shape

(24, 7)