<a href="https://colab.research.google.com/github/AVK48/AI-ML-JOURNEY/blob/Module-2/Linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
housing = pd.read_csv("/content/housing_sample.csv")
housing

    sqft  bedrooms  age_years  price_lakhs
0    800         2         15           40
1   1200         3         10           65
2   1500         3          8           78
3   2000         4          5          105
4   2500         4          3          130
5    900         2         20           45
6   1700         3          6           88
7   2200         4          4          115
8   1000         2         18           48
9   1350         3         12           70
10  1600         3          7           82
11  1900         4          9           98
12  2100         4          6          110
13   750         2         22           38
14  1450         3         11           74
15  1800         4         10           92
16  2400         4          2          128
17   950         2         16           47
18  1250         3         14           66
19  2050         4          7          107
20  1550         3          9           80
21  1100         2         13           52
22  1750         4          8           89
23  2300         4          3          122
24   850         2         19           42
25  1400         3         10           72
26  2150         4          5          112
27  1050         2         17           50
28  1650         3          7           85
29  1950         4          8          100

In [2]:
housing.head()

   sqft  bedrooms  age_years  price_lakhs
0   800         2         15           40
1  1200         3         10           65
2  1500         3          8           78
3  2000         4          5          105
4  2500         4          3          130

In [3]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sqft         30 non-null     int64
 1   bedrooms     30 non-null     int64
 2   age_years    30 non-null     int64
 3   price_lakhs  30 non-null     int64
dtypes: int64(4)
memory usage: 1.1 KB

In [4]:
housing.describe()

              sqft   bedrooms  age_years  price_lakhs
count    30.000000  30.000000  30.000000    30.000000
mean   1571.666667   3.133333  10.133333    81.000000
std     513.554774   0.819307   5.412204    27.877812
min     750.000000   2.000000   2.000000    38.000000
25%    1125.000000   2.250000   6.250000    55.250000
50%    1575.000000   3.000000   9.000000    81.000000
75%    1987.500000   4.000000  13.750000   103.750000
max    2500.000000   4.000000  22.000000   130.000000

In [5]:
housing.corr()

                 sqft  bedrooms  age_years  price_lakhs
sqft         1.000000  0.935365  -0.928444     0.998466
bedrooms     0.935365  1.000000  -0.859556     0.939046
age_years   -0.928444 -0.859556   1.000000    -0.932230
price_lakhs  0.998466  0.939046  -0.932230     1.000000

In [6]:
housing.isnull().sum()

sqft           0
bedrooms       0
age_years      0
price_lakhs    0
dtype: int64

In [7]:
housing.value_counts()

sqft  bedrooms  age_years  price_lakhs
750   2         22         38             1
800   2         15         40             1
850   2         19         42             1
900   2         20         45             1
950   2         16         47             1
1000  2         18         48             1
1050  2         17         50             1
1100  2         13         52             1
1200  3         10         65             1
1250  3         14         66             1
1350  3         12         70             1
1400  3         10         72             1
1450  3         11         74             1
1500  3         8          78             1
1550  3         9          80             1
1600  3         7          82             1
1650  3         7          85             1
1700  3         6          88             1
1750  4         8          89             1
1800  4         10         92             1
1900  4         9          98             1
1950  4         8          100            1
2000  4         5          105            1
2050  4         7          107            1
2100  4         6          110            1
2150  4         5          112            1
2200  4         4          115            1
2300  4         3          122            1
2400  4         2          128            1
2500  4         3          130            1
Name: count, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X = housing[['age_years','bedrooms','sqft']]
y = housing['price_lakhs']
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size =0.2, random_state = 45)

In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions)
print(y_test)

[125.12761259  51.12304165  72.28518959  42.81493881  34.86696131
  69.15569665]
16    128
27     50
25     72
5      45
13     38
9      70
Name: price_lakhs, dtype: int64

In [13]:
for feature,coef in zip(X.columns, model.coef_):
  print(f"{feature}:{coef}")
print(f"Intercept:{model.intercept_}")

age_years:-0.3601253225769716
bedrooms:1.776574667584974
sqft:0.04818484575585802
Intercept:3.097934750527614