<a href="https://colab.research.google.com/github/AVK48/AI-ML-JOURNEY/blob/pandas/pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/employees (1).csv')

In [ ]:
df

   emp_id     name department        salary   join_date       city
0     101    Alice         HR         52000  2022-03-15     Mumbai
1     102      Bob       Tech         85000  2021-07-01       Pune
2     103  Charlie       Tech           NaN  2020-11-20     Mumbai
3     104    Diana         HR         48000         NaN      Delhi
4     105      Eve    Finance         73000  2023-01-10        NaN
5     106      bob       Tech         85000  2021-07-01       Pune
6     107    Frank       Tech  not_a_number  2022-06-01  Bangalore

In [ ]:
df.head(3)

   emp_id     name department salary   join_date    city
0     101    Alice         HR  52000  2022-03-15  Mumbai
1     102      Bob       Tech  85000  2021-07-01    Pune
2     103  Charlie       Tech    NaN  2020-11-20  Mumbai

In [ ]:
df.tail(6)

   emp_id     name department        salary   join_date       city
1     102      Bob       Tech         85000  2021-07-01       Pune
2     103  Charlie       Tech           NaN  2020-11-20     Mumbai
3     104    Diana         HR         48000         NaN      Delhi
4     105      Eve    Finance         73000  2023-01-10        NaN
5     106      bob       Tech         85000  2021-07-01       Pune
6     107    Frank       Tech  not_a_number  2022-06-01  Bangalore

In [ ]:
df.head(3)
df.tail(3)

   emp_id   name department        salary   join_date       city
4     105    Eve    Finance         73000  2023-01-10        NaN
5     106    bob       Tech         85000  2021-07-01       Pune
6     107  Frank       Tech  not_a_number  2022-06-01  Bangalore

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.shape

(7, 6)

In [ ]:
df.columns

Index(['emp_id', 'name', 'department', 'salary', 'join_date', 'city'], dtype='object')

In [ ]:
df.columns[7]

IndexError: index 7 is out of bounds for axis 0 with size 6

In [ ]:
df.columns[5]

'city'

In [ ]:
df.dtypes

emp_id         int64
name          object
department    object
salary        object
join_date     object
city          object
dtype: object

In [ ]:
df.index

RangeIndex(start=0, stop=7, step=1)

In [ ]:
type(df['salary'])  #single square bracket prints the type series

pandas.core.series.Series

In [ ]:
type(df[['salary']])  #double square brackets prints the type dataframe

pandas.core.frame.DataFrame

In [ ]:
df[['name','salary']] #only needed from the list (name,salary)

      name        salary
0    Alice         52000
1      Bob         85000
2  Charlie           NaN
3    Diana         48000
4      Eve         73000
5      bob         85000
6    Frank  not_a_number

In [ ]:
df[['department','city']]

  department       city
0         HR     Mumbai
1       Tech       Pune
2       Tech     Mumbai
3         HR      Delhi
4    Finance        NaN
5       Tech       Pune
6       Tech  Bangalore

In [ ]:
df[['city','name']]

        city     name
0     Mumbai    Alice
1       Pune      Bob
2     Mumbai  Charlie
3      Delhi    Diana
4        NaN      Eve
5       Pune      bob
6  Bangalore    Frank

Dictionary to DataFrame

In [ ]:
data = {'Name':['jai','princi','guarv','av'],  #coverting dictionary to the data frame
        'age':[23,34,54,54],
        'address': ['wgl','hyd','krmg','viy']}
df2=pd.DataFrame(data)
df2

     Name  age address
0     jai   23     wgl
1  princi   34     hyd
2   guarv   54    krmg
3      av   54     viy

In [ ]:
type(df2) #type of the variable

pandas.core.frame.DataFrame

Age Inspection

In [ ]:
df2.age # same as df2['age']

0    23
1    34
2    54
3    54
Name: age, dtype: int64

In [ ]:
ages = df2.age
ages

0    23
1    34
2    54
3    54
Name: age, dtype: int64

In [ ]:
ages.mean()

np.float64(41.25)

In [ ]:
ages.describe()

count     4.000000
mean     41.250000
std      15.392098
min      23.000000
25%      31.250000
50%      44.000000
75%      54.000000
max      54.000000
Name: age, dtype: float64

read_csv

In [ ]:
df3 = pd.read_csv('/content/employees (1).csv',sep= '/t') #comma sepreated data

/tmp/ipykernel_1919/2451874851.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df3 = pd.read_csv('/content/employees (1).csv',sep= '/t')

In [ ]:
df3

       emp_id,name,department,salary,join_date,city
0              101,Alice,HR,52000,2022-03-15,Mumbai
1                102,Bob,Tech,85000,2021-07-01,Pune
2               103,Charlie,Tech,,2020-11-20,Mumbai
3                         104,Diana,HR,48000,,Delhi
4                 105,Eve,Finance,73000,2023-01-10,
5                106,bob,Tech,85000,2021-07-01,Pune
6  107,Frank,Tech,not_a_number,2022-06-01,Bangalore

In [ ]:
df3 = pd.read_csv('/content/employees (1).csv',sep= ',',usecols=['emp_id','salary','name'],dtype={"emp_id":str})

In [ ]:
df3

  emp_id     name        salary
0    101    Alice         52000
1    102      Bob         85000
2    103  Charlie           NaN
3    104    Diana         48000
4    105      Eve         73000
5    106      bob         85000
6    107    Frank  not_a_number

In [ ]:
df3.describe()

       emp_id   name salary
count       7      7      6
unique      7      7      5
top       101  Alice  85000
freq        1      1      2

Filtering

In [ ]:
df2[df2['age']>20] #for getting bigger than age 20

     Name  age address
0     jai   23     wgl
1  princi   34     hyd
2   guarv   54    krmg
3      av   54     viy

In [ ]:
df2['Name']!='guarv'

0     True
1     True
2    False
3     True
Name: Name, dtype: bool

In [ ]:
df2[df2['Name']!='guarv']

     Name  age address
0     jai   23     wgl
1  princi   34     hyd
3      av   54     viy

In [ ]:
(df['department']=='HR') & (df['city']== 'Mumbai')

0     True
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [ ]:
df[(df['department']=='HR') & (df['city']== 'Mumbai')]

   emp_id   name department salary   join_date    city
0     101  Alice         HR  52000  2022-03-15  Mumbai

In [ ]:
df[(df['department']=='HR') | (df['city']== 'Mumbai')]

   emp_id     name department salary   join_date    city
0     101    Alice         HR  52000  2022-03-15  Mumbai
2     103  Charlie       Tech    NaN  2020-11-20  Mumbai
3     104    Diana         HR  48000         NaN   Delhi

In [ ]:
df[(df['department']!="HR")]

   emp_id     name department        salary   join_date       city
1     102      Bob       Tech         85000  2021-07-01       Pune
2     103  Charlie       Tech           NaN  2020-11-20     Mumbai
4     105      Eve    Finance         73000  2023-01-10        NaN
5     106      bob       Tech         85000  2021-07-01       Pune
6     107    Frank       Tech  not_a_number  2022-06-01  Bangalore

In [ ]:
df[(df['department'].isin(['HR','Finance']))]

   emp_id   name department salary   join_date    city
0     101  Alice         HR  52000  2022-03-15  Mumbai
3     104  Diana         HR  48000         NaN   Delhi
4     105    Eve    Finance  73000  2023-01-10     NaN

In [ ]:
df[~(df['department'].isin(['HR','Finance']))]

   emp_id     name department        salary   join_date       city
1     102      Bob       Tech         85000  2021-07-01       Pune
2     103  Charlie       Tech           NaN  2020-11-20     Mumbai
5     106      bob       Tech         85000  2021-07-01       Pune
6     107    Frank       Tech  not_a_number  2022-06-01  Bangalore

Sorting

In [ ]:
df2.sort_values('age')

     Name  age address
0     jai   23     wgl
1  princi   34     hyd
2   guarv   54    krmg
3      av   54     viy

In [ ]:
df2.sort_values('age',ascending=False)

     Name  age address
3      av   54     viy
2   guarv   54    krmg
1  princi   34     hyd
0     jai   23     wgl