<a href="https://colab.research.google.com/github/AVK48/AI-ML-JOURNEY/blob/AVK48-pandas/Pandas(Aggregation%2C_GroupBy%2C_Merging).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

GROUPBY

In [ ]:
import pandas as pd
data = {
    "name":       ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank"],
    "department": ["HR", "Tech", "Tech", "HR", "Finance", "Tech"],
    "salary":     [52000, 85000, 91000, 48000, 73000, 88000],
    "rating":     [4, 5, 5, 3, 4, 4]
}
df = pd.DataFrame(data)

In [ ]:
df.groupby("department")["salary"].mean()

department
Finance    73000.0
HR         50000.0
Tech       88000.0
Name: salary, dtype: float64

In [ ]:
df.groupby("department")["rating"].mean()

department
Finance    4.000000
HR         3.500000
Tech       4.666667
Name: rating, dtype: float64

In [ ]:
df.groupby("department")["rating"].count()

department
Finance    1
HR         2
Tech       3
Name: rating, dtype: int64

In [ ]:
df.groupby("department")["salary"].count()

department
Finance    1
HR         2
Tech       3
Name: salary, dtype: int64

In [ ]:
df.groupby("department")["salary"].max()

department
Finance    73000
HR         52000
Tech       91000
Name: salary, dtype: int64

In [ ]:
df.groupby("department")["salary"].min().index

Index(['Finance', 'HR', 'Tech'], dtype='object', name='department')

In [ ]:
df["department"].value_counts(normalize=True)

department
Tech       0.500000
HR         0.333333
Finance    0.166667
Name: proportion, dtype: float64

In [ ]:
summary =df.groupby("department").aggregate(headcount=("name","count"),
                                            avg_salary = ("salary","mean"),
                                            max_salary= ("salary","max"),
                                            avg_rating =("rating","mean"))
summary

            headcount  avg_salary  max_salary  avg_rating
department
Finance             1     73000.0       73000    4.000000
HR                  2     50000.0       52000    3.500000
Tech                3     88000.0       91000    4.666667

In [ ]:
df["department"].unique()

array(['HR', 'Tech', 'Finance'], dtype=object)

In [ ]:
df["department"].nunique()

3

In [ ]:
df["department"].max()

'Tech'

In [ ]:
idx =df.groupby("department")["salary"].idxmax()
idx

department
Finance    4
HR         0
Tech       2
Name: salary, dtype: int64

In [ ]:
top_earners=df.loc[idx]
top_earners

      name department  salary  rating
4      Eve    Finance   73000       4
0    Alice         HR   52000       4
2  Charlie       Tech   91000       5

In [ ]:
import numpy as np
data2 = {
    "name":       ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank",'smith','klassen','Aurora',"Franklin",np.nan],
    "department": ["HR", "Tech", "Tech", "HR", "Finance", "Tech",np.nan,'HR',"Finance",np.nan,np.nan],
    "salary":     [52000, 85000, 91000, 48000, 73000, 88000,np.nan,np.nan,74000,50000,np.nan],
    "rating":     [4, 5, 5, 3, 4, 4,np.nan,4,np.nan,3,np.nan]
}
df2= pd.DataFrame(data2)
df2

        name department   salary  rating
0      Alice         HR  52000.0     4.0
1        Bob       Tech  85000.0     5.0
2    Charlie       Tech  91000.0     5.0
3      Diana         HR  48000.0     3.0
4        Eve    Finance  73000.0     4.0
5      Frank       Tech  88000.0     4.0
6      smith        NaN      NaN     NaN
7    klassen         HR      NaN     4.0
8     Aurora    Finance  74000.0     NaN
9   Franklin        NaN  50000.0     3.0
10       NaN        NaN      NaN     NaN

In [ ]:
df2.isnull().sum()

name          1
department    3
salary        3
rating        3
dtype: int64

In [ ]:
df2.dropna()

      name department   salary  rating
0    Alice         HR  52000.0     4.0
1      Bob       Tech  85000.0     5.0
2  Charlie       Tech  91000.0     5.0
3    Diana         HR  48000.0     3.0
4      Eve    Finance  73000.0     4.0
5    Frank       Tech  88000.0     4.0

In [ ]:
import numpy as np
data2 = {
    "name":       ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank",'smith','klassen','Aurora',"Franklin",np.nan],
    "department": ["HR", "Tech", "Tech", "HR", "Finance", "Tech",np.nan,'HR',"Finance",np.nan,np.nan],
    "salary":     [52000, 85000, 91000, 48000, 73000, 88000,np.nan,np.nan,74000,50000,np.nan],
    "rating":     [4, 5, 5, 3, 4, 4,np.nan,4,np.nan,3,np.nan]
}
df2= pd.DataFrame(data2)
df2

        name department   salary  rating
0      Alice         HR  52000.0     4.0
1        Bob       Tech  85000.0     5.0
2    Charlie       Tech  91000.0     5.0
3      Diana         HR  48000.0     3.0
4        Eve    Finance  73000.0     4.0
5      Frank       Tech  88000.0     4.0
6      smith        NaN      NaN     NaN
7    klassen         HR      NaN     4.0
8     Aurora    Finance  74000.0     NaN
9   Franklin        NaN  50000.0     3.0
10       NaN        NaN      NaN     NaN

In [ ]:
df2.dropna(how = "all")

       name department   salary  rating
0     Alice         HR  52000.0     4.0
1       Bob       Tech  85000.0     5.0
2   Charlie       Tech  91000.0     5.0
3     Diana         HR  48000.0     3.0
4       Eve    Finance  73000.0     4.0
5     Frank       Tech  88000.0     4.0
6     smith        NaN      NaN     NaN
7   klassen         HR      NaN     4.0
8    Aurora    Finance  74000.0     NaN
9  Franklin        NaN  50000.0     3.0

In [ ]:
df2.dropna(how='any')

      name department   salary  rating
0    Alice         HR  52000.0     4.0
1      Bob       Tech  85000.0     5.0
2  Charlie       Tech  91000.0     5.0
3    Diana         HR  48000.0     3.0
4      Eve    Finance  73000.0     4.0
5    Frank       Tech  88000.0     4.0

In [ ]:
df2

        name department   salary  rating
0      Alice         HR  52000.0     4.0
1        Bob       Tech  85000.0     5.0
2    Charlie       Tech  91000.0     5.0
3      Diana         HR  48000.0     3.0
4        Eve    Finance  73000.0     4.0
5      Frank       Tech  88000.0     4.0
6      smith        NaN      NaN     NaN
7    klassen         HR      NaN     4.0
8     Aurora    Finance  74000.0     NaN
9   Franklin        NaN  50000.0     3.0
10       NaN        NaN      NaN     NaN

In [ ]:
df2['salary'].fillna(df2['salary'].median())

0     52000.0
1     85000.0
2     91000.0
3     48000.0
4     73000.0
5     88000.0
6     73500.0
7     73500.0
8     74000.0
9     50000.0
10    73500.0
Name: salary, dtype: float64

In [ ]:
df2.fillna({'salary':7,'rating':2})

        name department   salary  rating
0      Alice         HR  52000.0     4.0
1        Bob       Tech  85000.0     5.0
2    Charlie       Tech  91000.0     5.0
3      Diana         HR  48000.0     3.0
4        Eve    Finance  73000.0     4.0
5      Frank       Tech  88000.0     4.0
6      smith        NaN      7.0     2.0
7    klassen         HR      7.0     4.0
8     Aurora    Finance  74000.0     2.0
9   Franklin        NaN  50000.0     3.0
10       NaN        NaN      7.0     2.0

In [ ]:
df2.dropna(inplace=True)
df2

      name department   salary  rating
0    Alice         HR  52000.0     4.0
1      Bob       Tech  85000.0     5.0
2  Charlie       Tech  91000.0     5.0
3    Diana         HR  48000.0     3.0
4      Eve    Finance  73000.0     4.0
5    Frank       Tech  88000.0     4.0

In [ ]:
data4 = {
    "name":       ["Alice", "Bob", "Bob", "Diana", "Eve", "Frank"],
    "department": ["HR", "Tech", "Tech", "HR", "Finance", "Tech"],
    "salary":     [52000, 85000, 85000, None, 73000, 91000],
    "rating":     [4, 5, 5, 3, None, 4]
}
df4 = pd.DataFrame(data4)
df4

    name department   salary  rating
0  Alice         HR  52000.0     4.0
1    Bob       Tech  85000.0     5.0
2    Bob       Tech  85000.0     5.0
3  Diana         HR      NaN     3.0
4    Eve    Finance  73000.0     NaN
5  Frank       Tech  91000.0     4.0

In [ ]:
df4.duplicated().sum()

np.int64(1)

In [ ]:
df4.drop_duplicates()

    name department   salary  rating
0  Alice         HR  52000.0     4.0
1    Bob       Tech  85000.0     5.0
3  Diana         HR      NaN     3.0
4    Eve    Finance  73000.0     NaN
5  Frank       Tech  91000.0     4.0

JOINING AND MARGING

In [ ]:
customers = pd.DataFrame({
    "cust_id":   ["C01", "C02", "C03", "C04"],
    "name":      ["Alice", "Bob", "Charlie", "Diana"],
    "city":      ["Mumbai", "Pune", "Mumbai", "Delhi"]
})

orders = pd.DataFrame({
    "order_id":  ["O1001", "O1002", "O1003", "O1004", "O1005"],
    "cust_id":   ["C01", "C03", "C01", "C99", "C02"],
    "amount":    [5000, 3200, 1800, 9000, 4500],
    "status":    ["completed", "completed", "cancelled", "completed", "completed"]
})

Concat

In [ ]:
df_q1=pd.DataFrame({"product":["A","B"],"sales":[100,200]})
df_q2=pd.DataFrame({"product":["A","C"],"sales":[300,400]})

In [ ]:
pd.concat([df_q1,df_q2])

  product  sales
0       A    100
1       B    200
0       A    300
1       C    400

In [ ]:
pd.concat([df_q1,df_q2],ignore_index=True)

  product  sales
0       A    100
1       B    200
2       A    300
3       C    400