In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd

In [ ]:
df = pd.read_csv("/content/customer (1).csv")

In [ ]:
df.head()

   customer_id  age  monthly_spend  support_tickets  tenure_months  churned
0         1001   25           20.5                5              3        1
1         1002   45           80.0                0             28        0
2         1003   35           40.2                3             11        1
3         1004   50           95.5                0             36        0
4         1005   23           15.0                6              2        1

In [ ]:
X = df.drop(columns=['customer_id','churned'])
X

   age  monthly_spend  support_tickets  tenure_months
0   25           20.5                5              3
1   45           80.0                0             28
2   35           40.2                3             11
3   50           95.5                0             36
4   23           15.0                6              2

In [ ]:
y =df['churned']
y

0    1
1    0
2    1
3    0
4    1
Name: churned, dtype: int64

In [ ]:
type(train_test_split(X,y,test_size=0.2))

list

In [ ]:
train_test_split(X,y,test_size=0.2)[0].shape

(4, 4)

In [ ]:
train_test_split(X,y,test_size=0.2)[1].shape

(1, 4)

In [ ]:
train_test_split(X,y,test_size=0.2)[2].shape

(4,)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train.index

Index([4, 2, 0, 3], dtype='int64')

In [ ]:
y_train.index

Index([4, 2, 0, 3], dtype='int64')

In [ ]:
y_train.value_counts()

churned
1    3
0    1
Name: count, dtype: int64

In [ ]:
y_test.value_counts()

churned
0    1
Name: count, dtype: int64